- name: Loop Demo
  hosts: localhost
  tasks:
    - name: Print Fruits
      ansible.builtin.debug:
        msg: "Fruit Name - {{ item }}"
      loop:
        - apple
        - banana
        - orange

    - name: Print Fruits with Quantity
      ansible.builtin.debug:
        msg: "Fruit Name - {{ item.name }}, Quantity - {{ item.quantity }}"
      loop:
        - { name: apple , quantity: 10 }
        - { name: banana , quantity: 20 }
        - { name: orange , quantity: 30 }    

#Iteration of tasks until condition fails

#loop

# print "i love my country" (5 times)

# print(1)
# echo 1  - write it 5 times

# for (i=1;i<=5;i++)
#  system.print("i love my country")

# Dry run:
# Iteration -1

#  i=1 ; i<=5 ~ 1<=5 ?? True
#   i love my country

# Iteration -2
#  i=1+1=2
#  i=2 ; i<=5 ~ 2<=5 ?? True
#   i love my country

# Iteration -nth
#  i=5+1=6
#  i=6; 6<=5 ?? False  

 